<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>intel_sys_bringup</name>
  <version>1.0.0</version>
  <description>Top-level launch scripts and unified system bringup for Intel Sys robot</description>
  <maintainer email="aahil.aref@gmail.com">Aahil Shaikh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>intel_sys_interfaces</depend>
  <depend>intel_sys_hardware</depend>
  <depend>intel_sys_description</depend>
  <depend>intel_sys_localization</depend>
  <depend>intel_sys_navigation</depend>
  <depend>intel_sys_sim</depend>
  <depend>teleop_twist_keyboard</depend>
  <depend>teleop_twist_joy</depend>
  <depend>rviz2</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
