x-nvidia-gpu: &nvidia-gpu
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all,graphics,display,utility,compute
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  intel-sys:
    <<: *nvidia-gpu
  intel-sys-sim:
    <<: *nvidia-gpu
  intel-sys-rover:
    <<: *nvidia-gpu
