services:
  intel-sys:
    container_name: intel-sys
    build:
      context: .
      args:
        TARGETARCH: ${TARGETARCH:-amd64}
      network: host
    image: intel-sys:${TARGETARCH:-amd64}
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ./:/workspaces/intel_sys
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/udev:/run/udev:ro
      - /dev:/dev
    stdin_open: true
    tty: true
    runtime: ${DOCKER_RUNTIME:-runc}
